backbone: "CLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
gpu: 5
num_workers: 8
prec: "amp"

num_epochs: 10
batch_size: 128
micro_batch_size: 128
lr: 0.01
adaptformer: True
# vpt_deep: True
weight_decay: 5e-4
momentum: 0.9
loss_type: "LA"
classifier: "CosineClassifier"

multi_model: True
dual_prompt: False
# vis_num_tokens: 10
txt_num_tokens: 16

init_head: "none"
tte: False
expand: 24